### ISSUE TITLE
Typescript Definitions for OTPAuth

### ISSUE THREAD

**Issue by binaek89** [hectorm/otpauth#1]

**Comment by zant95** [comment]
I'm sorry, but I have no experience with TypeScript, so I currently have no plans to add this. However, any pull request will be welcomed.

**Comment by me7** [comment]
i submit pull request in #4

**Comment by hectorm** [comment]
I think those definitions are incorrect and incomplete. I just added my own definitions (9607d1c3d502467ab2e600f45250db7964226d4f), but as I have no experience with TypeScript I hope you can confirm that they are correct.

**Comment by hectorm** [comment]
Solved in v4.0.0.
