### ISSUE TITLE
Consider using Pagic to build the website?

### ISSUE THREAD

**Issue by xcatliu** [hectorm/otpauth#11]
[Pagic](https://pagic.org) is a static site generator powered by Deno + React

Here are some demos:

- [pagic.org](https://pagic.org)
- [Deno X ranking](https://yoshixmk.github.io/deno-x-ranking/)
- [TypeScript 入门教程](https://ts.xcatliu.com/)

If it is possible to use pagic to build the website, I would like to create the pull-request

**Comment by hectorm** [comment]
I looked at Pagic and it's a very nice option, however right now I'm using [documentation](https://github.com/documentationjs/documentation) to generate the [documentation page](https://hectorm.github.io/otpauth/) [automatically](https://github.com/hectorm/otpauth/blob/v6.0.7/package.json#L54) from [JSDoc annotations](https://github.com/hectorm/otpauth/blob/v6.0.7/src/otp.js#L20-L30), this way I can always keep the documentation up to date with the source code without having to maintain it separately. Could this be done with Pagic right now?
