### ISSUE TITLE
validation may be vulnerable to timing attacks

### ISSUE THREAD

**Issue by jawj** [hectorm/otpauth#13]
Seems to me that the validate method may be vulnerable to timing attacks, since it uses a naive [string equality test](https://github.com/hectorm/otpauth/blob/f9c9a3bddd7c226785b9c92fb6a37569c5d4646c/src/otp.js#L143).

Can you replace this with [`crypto.timingSafeEqual`](https://nodejs.org/api/crypto.html#crypto_crypto_timingsafeequal_a_b), or would you accept a pull request if I have a go at it?

**Comment by hectorm** [comment]
That's interesting, thanks for sharing this.

I will definitely use `crypto.timingSafeEqual` for Node.js. For Deno and browsers, do you think [this shim](https://github.com/crypto-browserify/timing-safe-equal/blob/master/browser.js#L12-L22) would be a good alternative?

**Comment by jawj** [comment]
Great. The shim looks pretty sane, so yes.

**Comment by hectorm** [comment]
Let me know if https://github.com/hectorm/otpauth/commit/68f50b66b1c481a9b221fec28e40fcb67dd114b6 would be enough to solve the problem.

**Comment by jawj** [comment]
Buffers must be equal length:

```
> c.timingSafeEqual(Buffer.from('xyz'), Buffer.from('xy'))
Uncaught [RangeError: Input buffers must have the same byte length] {
  code: 'ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH'
}
```

Since the length of the OTP is not a secret, it's probably safe to test for equal lengths first, e.g.

```
if (token.length !== generatedToken.length) return null;
```

**Comment by hectorm** [comment]
Done. Thanks again!

**Comment by jawj** [comment]
I now note that in `validate` there's an early return on matching tokens, which potentially leaks information about where in the sequence the match occurred.

```
for (let i = counter - window; i <= counter + window; ++i) {
  const generatedToken = HOTP.generate({
    secret,
    algorithm,
    digits: token.length,
    counter: i
  });

  if (
    token.length === generatedToken.length
    && Crypto.timingSafeEqual(token, generatedToken)
  ) {
    return i - counter;  // <- ** HERE **
  }
}

return null;
```

Can you fix that so that validate always takes the same time?

**Comment by hectorm** [comment]
Absolutely correct, thanks for the warning.

Could you confirm that https://github.com/hectorm/otpauth/commit/91fa2fadab4b0b4bc9f1e71e4298ea3fe9ac3790 definitely solves the validation in constant time?

**Comment by hectorm** [comment]
I've also noticed that the length comparison is not really necessary because it will always be true since the `HOTP.generate` method within the loop is always called with the `digits` property with the length of the token to be validated.

**Comment by jawj** [comment]
The fix looks right, I think, thanks.

But isn't that a huge security hole right there in the static variety of `generate`? If you're validating with that version, can't I can just put in a one-digit code and have a 10% chance of getting it right (or possibly even a zero-digit code and always get it right)?

I see this is mitigated in the instance version by padding the token up to `this.digits` length, in which case yes, your point about the length comparison seems to hold. But I really wouldn't let anyone call static `generate` as things stand.

**Comment by hectorm** [comment]
The use case of the static variant is very limited since it doesn't know the expected token length so the developer must check it first. In most cases it's the instance method the one that should be used. Maybe this should have been part of the private API so that nobody uses it carelessly.

One solution that occurs to me is to add the `digits` argument to the static method and perform the check myself instead of relying on the developer to do this.

```diff
diff --git a/src/otp.js b/src/otp.js
index cad52bd..4675ddc 100644
--- a/src/otp.js
+++ b/src/otp.js
@@ -119,6 +119,7 @@ export class HOTP {
         * Validates an HOTP token.
         * @param {Object} config Configuration options.
         * @param {string} config.token Token value.
+        * @param {number} config.digits Token length.
         * @param {Secret} config.secret Secret key.
         * @param {string} [config.algorithm='SHA1'] HMAC hashing algorithm.
         * @param {number} [config.counter=0] Counter value.
@@ -127,18 +128,22 @@ export class HOTP {
         */
        static validate({
                token,
+               digits,
                secret,
                algorithm,
                counter = defaults.counter,
                window = defaults.window
        }) {
+               // Return early if the token length does not match the digit number.
+               if (token.length !== digits) return null;
+
                let delta = null;
 
                for (let i = counter - window; i <= counter + window; ++i) {
                        const generatedToken = HOTP.generate({
+                               digits,
                                secret,
                                algorithm,
-                               digits: token.length,
                                counter: i
                        });
 
@@ -164,7 +169,8 @@ export class HOTP {
                window
        }) {
                return HOTP.validate({
-                       token: Utils.pad(token, this.digits),
+                       token,
+                       digits: this.digits,
                        secret: this.secret,
                        algorithm: this.algorithm,
                        counter,
@@ -290,6 +296,7 @@ export class TOTP {
         * Validates a TOTP token.
         * @param {Object} config Configuration options.
         * @param {string} config.token Token value.
+        * @param {number} config.digits Token length.
         * @param {Secret} config.secret Secret key.
         * @param {string} [config.algorithm='SHA1'] HMAC hashing algorithm.
         * @param {number} [config.period=30] Token time-step duration.
@@ -299,6 +306,7 @@ export class TOTP {
         */
        static validate({
                token,
+               digits,
                secret,
                algorithm,
                period = defaults.period,
@@ -307,6 +315,7 @@ export class TOTP {
        }) {
                return HOTP.validate({
                        token,
+                       digits,
                        secret,
                        algorithm,
                        counter: Math.floor(timestamp / 1000 / period),
@@ -328,7 +337,8 @@ export class TOTP {
                window
        }) {
                return TOTP.validate({
-                       token: Utils.pad(token, this.digits),
+                       token,
+                       digits: this.digits,
                        secret: this.secret,
                        algorithm: this.algorithm,
                        period: this.period,
```

**Comment by hectorm** [comment]
I've released a new version which I think solves all your concerns. Thank you for your helpful feedback.
