### ISSUE TITLE
Problem with Vercel Edge Runtime

### ISSUE THREAD

**Issue by legowerewolf** [hectorm/otpauth#146]
The Edge Runtime is a browser-like runtime (no Node APIs available), but it also explicitly disallows dynamic code execution (no `eval()`). Could you add a way to import the browser-safe methods directly without relying on the Node check that uses `eval()`?

[Edge Runtime limitations](https://vercel.com/docs/concepts/functions/edge-functions/limitations)

**Comment by hectorm** [comment]
Could you confirm if `9.0.0-beta.1` version fixes this problem?

**Comment by legowerewolf** [comment]
It does, thank you!

**Comment by hectorm** [comment]
Thanks for testing it, could you provide me with a code snippet to do some testing to make sure my changes cause as few incompatibilities as possible?

**Comment by legowerewolf** [comment]
I don't know the best way to integrate it would be - there's connections to the Jest and Vitest frameworks, but it doesn't look like you use that. Further documentation for the runtime is available here: https://edge-runtime.vercel.app/

I think you could [import the module](https://edge-runtime.vercel.app/packages/runtime) and check to see if the constructor fails when you give it something even as simple as `new TOTP()`, but I've never worked with the runtime in this context before. I just deploy stuff on it through Vercel.

**Comment by hectorm** [comment]
Finally I have decided to create specific bundles for Node.js and for the rest of platforms to avoid doing tricks in a unified bundle. Unfortunately I have not found a way to set a specific condition for Vercel in the `exports` field of the `package.json` file and instead it is picking the `node` condition.

For the moment in Vercel Edge OTPAuth can be imported using the `otpauth/dist/otpauth.esm.js` path directly.

**Comment by legowerewolf** [comment]
What version should I depend on for this? One of the 9.0.0-betas? or 8.0.3?

**Comment by hectorm** [comment]
In your case the latest beta version should work fine importing `otpauth/dist/otpauth.esm.js` directly.
