### ISSUE TITLE
error with Deno final bundle!

### ISSUE THREAD

**Issue by michailVestnik** [hectorm/otpauth#16]
If i run your simple example all wortks fine. 
But if i made bundle (deno bundle 'url/path/to/mod.ts') and run again i see the error1
Screenshot with error https://user-images.githubusercontent.com/75129392/102112163-a9c31a00-3e7a-11eb-8f85-14eb57b4db79.jpg

**Comment by hectorm** [comment]
I was able to reproduce a similar error.

With the following code:
```typescript
// @deno-types="https://deno.land/x/otpauth/types/index.d.ts"
import * as OTPAuth from 'https://deno.land/x/otpauth/dist/otpauth.esm.js';

let totp = OTPAuth.URI.parse('otpauth://totp/ACME:AzureDiamond?issuer=ACME&secret=NB2W45DFOIZA&algorithm=SHA1&digits=6&period=30');
console.log(totp);
```

When I run:
```shell
deno bundle ./app.ts ./app.bundle.js
deno run ./app.bundle.js
```

I get the following error:
```
error: Uncaught ReferenceError: parse is not defined
let totp = parse('otpauth://totp/ACME:AzureDiamond?issuer=ACME&secret=NB2W45DFOIZA&algorithm=SHA1&digits=6&period=30');
           ^
    at file:///home/hectorm/Projects/deno-otpauth/app.bundle.js:1512:12
```

However, if I change the way the module is imported, it works correctly.
```typescript
// @deno-types="https://deno.land/x/otpauth/types/index.d.ts"
import { URI } from 'https://deno.land/x/otpauth/dist/otpauth.esm.js';

let totp = URI.parse('otpauth://totp/ACME:AzureDiamond?issuer=ACME&secret=NB2W45DFOIZA&algorithm=SHA1&digits=6&period=30');
console.log(totp);
```

Could you confirm whether the way OTPAuth is being imported is what is causing your error?

**Comment by michailVestnik** [comment]
Yes, if i run this example with OTPAuth i see the error.

Screenshot with bundle and error
https://user-images.githubusercontent.com/75129392/102188550-c9992300-3ef8-11eb-9058-2e0bc3fc5111.jpg

Screenshot with bundle without error
https://user-images.githubusercontent.com/75129392/102188666-f2211d00-3ef8-11eb-8d06-3fdf0617afc6.jpg

please note the first line in the screenshot!

**Comment by hectorm** [comment]
In the first screenshot you should import the library like this (however, it will probably fail with the `parse is not defined` error):
```
import * as OTPAuth from './otpauth.js';
```

Anyway in my previous message I meant that you should try to change in your **own** code the way OTPAuth is imported based on the two examples I indicated. I suspect that it's a bug in Deno.

If you provide me with a test project that reproduces the problem it would be helpful.
