### ISSUE TITLE
npm package is empty

### ISSUE THREAD

**Issue by mdantonio** [hectorm/otpauth#18]
Hello.
I was trying to upgrade to 7.0.1 but found the package mostly empty, it only contains 3 files:

```
$ ls node_modules/otpauth/
LICENSE.md  package.json  README.md
```

This is also confirmed by https://www.npmjs.com/package/otpauth/v/7.0.1:

Unpacked Size: 6.85 kB
Total Files: 3

as a comparison 7.0.0 (https://www.npmjs.com/package/otpauth/v/7.0.0) was:

Unpacked Size: 581 kB
Total Files: 51

**Comment by hectorm** [comment]
Thank you very much for the warning. I set incorrect file patterns in the package.json. I just fixed it and released a new version.

**Comment by mdantonio** [comment]
Thank you for the new release, it works well now
