### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by s-pcode** [hectorm/otpauth#22]
This might be a weird issue, but I'm currently facing this issue with only android devices. For iPhone, the whole process works seamlessly.
In the case of android, the QR is scanned correctly and the account is added to google authenticator. While verifying the token, it always fails. Tried the exact same procedure on iPhone and it worked perfectly right. Can you please help me as I have no clue about what is wrong?

The code is exactly the same as mentioned in the documentation.

Thanks in advance.

**Comment by hectorm** [comment]
Hi, could you please provide some code to help me reproduce this problem?

**Comment by s-pcode** [comment]
Please find the code below. The order is I generate a temp secret , then verify and after verification store the secret and do further validation when required.

`
const getGenerateSecret = async (req, res, next) => {
  try {
    let user = req.user;
    if (user.mfa.secret != null && user.mfa.secret != '') {
      let responseObject = {
        status: false,
        message: 'Secret already generated',
        data: {},
      };
      return res.json(responseObject).status(401);
    } else {
      let tempSecret = crypto.randomBytes(20).toString('hex');
      tempSecret = tempSecret.replace(/[^a-zA-Z2-7]/g, 'k');
      let secret = otpAuth.Secret.fromBase32(tempSecret);
      let totp = new otpAuth.TOTP({
        issuer: 'hello.world',
        label: `${user.email}`,
        algorithm: 'SHA256',
        digits: 6,
        period: 30,
        secret, // or "OTPAuth.Secret.fromBase32('NB2W45DFOIZA')"
      });
      await User.updateOne(
        { _id: user._id },
        { $set: { 'mfa.tempSecret': tempSecret } }
      );
      let responseObject = {
        status: true,
        message: 'Secret generated successfully',
        data: {
          qrCode: totp.toString(),
        },
      };
      return res.json(responseObject).status(200);
    }
  } catch (err) {
    console.log(err.message);
    console.log(err.stack);
    let responseObject = {
      status: false,
      message: 'Something went wrong',
      data: err.message,
    };
    return res.json(responseObject).status(504);
  }
};

const postValidateTOTP = async (req, res, next) => {
  try {
    let user = req.user;
    let { token } = req.body;
    console.log(token);
    console.log(user.mfa);
    let secret = otpAuth.Secret.fromBase32(user.mfa.secret);
    let totp = new otpAuth.TOTP({
      issuer: 'hello.world',
      label: `${user.email}`,
      algorithm: 'SHA256',
      digits: 6,
      period: 30,
      secret, // or "OTPAuth.Secret.fromBase32('NB2W45DFOIZA')"
    });

    let validate = totp.validate({ token });
    console.log(validate);
    if (validate == 0 || Math.abs(validate) == 1) {
      let responseObject = {
        status: true,
        message: 'Authenticated successfully',
        data: {},
      };

      return res.json(responseObject).status(200);
    } else {
      let responseObject = {
        status: false,
        message: 'Invalid Token',
        data: {},
      };
      return res.json(responseObject).status(400);
    }
  } catch (err) {
    let responseObject = {
      status: false,
      message: 'Something went wrong',
      data: err.message,
    };
    return res.json(responseObject).status(504);
  }
};
const postVerifyTOTP = async (req, res, next) => {
  try {
    let user = req.user;
    let { token } = req.body;
    let secret = otpAuth.Secret.fromBase32(user.mfa.tempSecret);
    let totp = new otpAuth.TOTP({
      issuer: 'hello.world',
      label: `${user.email}`,
      algorithm: 'SHA256',
      digits: 6,
      period: 30,
      secret, // or "OTPAuth.Secret.fromBase32('NB2W45DFOIZA')"
    });
    let validate = totp.validate({ token });
    let newSecret = user.mfa.tempSecret;

    if (validate == 0 || Math.abs(validate) == 1) {
      await User.updateOne(
        { _id: user._id },
        {
          $set: {
            'mfa.secret': newSecret,
            'mfa.tempSecret': '',
            'mfa.enabled': true,
          },
        }
      );
      let responseObject = {
        status: true,
        message: 'Authenticated successfully',
        data: {},
      };
      return res.json(responseObject).status(200);
    } else {
      let responseObject = {
        status: false,
        message: 'Invalid Token',
        data: {},
      };
      return res.json(responseObject).status(400);
    }
  } catch (err) {
    console.log(err.stack);
    let responseObject = {
      status: false,
      message: 'Something went wrong',
      data: err.message,
    };
    return res.json(responseObject).status(504);
  }
};
`

**Comment by hectorm** [comment]
On which Android version and browser version are you running this code?
Note also that TOTP is time sensitive, the environment where this code is executed must have the clock in sync.

**Comment by s-pcode** [comment]
Tested on the following devices:
Android: 10 & 11
Browser: Chrome & Brave latest
We tested the code locally and also in AWS EC2 (Ohio region).

Could not verify the code for android devices but worked fine for iPhones.

**Comment by hectorm** [comment]
The test suite passes without errors on the latest versions of Chrome and Brave on Android 10, so I think the bug is somewhere in your code and not in OTPAuth itself.

<details>
<summary>Chrome 97 on Android 10</summary>

![](https://user-images.githubusercontent.com/852266/151660116-b43a7d90-969c-460d-b82c-73e1f07c1aa5.png)

</details>

<details>
<summary>Brave 1.34 (based on Chromium 97) on Android 10</summary>

![](https://user-images.githubusercontent.com/852266/151660114-6d7aba83-9822-41b1-b589-93b330f99172.png)

</details>

By just looking at your code I can't identify the problem.

Would it be possible for you to provide a code snippet as simple as possible that reproduces the problem and that I can easily run myself in a test environment?

**Comment by s-pcode** [comment]
We figured out the issue and solved it. The issue was with the algorithm that we were passing in the options. For SHA256, this error was occurring but when changed to default SHA1 it worked perfectly fine.

Thanks for your support. 👍
