### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by worldpeaceenginelabs** [hectorm/otpauth#227]
Thanks for this cool library. 🙏👍
But is there a reason that it does not use a QR code? Security? Code issues?
Maybe i am spoiled but... 

Kind regards

**Comment by hectorm** [comment]
A QR code is nothing more than a way to encode text. This library does not generate or read QR codes as this is outside the scope of the project, there are already excellent libraries for this functionality that can be complemented with OTPAuth.
