### ISSUE TITLE
Token validation returns null if the token is of Number type and not string

### ISSUE THREAD

**Issue by igbominadeveloper** [hectorm/otpauth#23]
```js
 static validate({
    token,
    secret,
    algorithm,
    digits,
    counter = HOTP.defaults.counter,
    window = HOTP.defaults.window,
  }) {
    // Return early if the token length does not match the digit number.
    if (token.length !== digits) return null;
```

**Comment by igbominadeveloper** [comment]
> ```js
>  static validate({
>     token,
>     secret,
>     algorithm,
>     digits,
>     counter = HOTP.defaults.counter,
>     window = HOTP.defaults.window,
>   }) {
>     // Return early if the token length does not match the digit number.
>     if (token.length !== digits) return null;
> ```

since it is impossible to check the length of an argument of number type

**Comment by hectorm** [comment]
I'm closing this issue as stated in https://github.com/hectorm/otpauth/pull/24#issuecomment-1028212514.

**Comment by akama-aka** [comment]
I still get this issue. Dont even care if its a String, Number, Valid, Invalid, Timestamp set, Timestamp not set, Length right, Length not right just get everytime null back in delta.
Logs:
![grafik](https://github.com/hectorm/otpauth/assets/105487011/30a60284-db6b-4acf-a780-95133363a798)

Code:

```js
if(!otpc || !secret) { // both are true
        return false;
    }
    otpc = otpc.toString(); // Tried with toInt... and toString...
    console.log(otpc.length) // Length = 6
    let totp = new OTPAuth.TOTP({
        issuer: "my_page.com",
        label: "myPage",
        algorithm: "SHA1",
        period: 30,
        digits: 6,
        secret: OTPAuth.Secret.fromBase32(secret),
    });
    let code = totp.generate(); // Valid result
    console.log("Token: "+code); // Valid result
    console.log(OTPAuth.Secret.fromBase32(secret));// Valid Result
    let delta = totp.validate({token: otpc, window: 1}); // Debugger Says delta null
    console.log("DELTE: "+delta); // null
    return delta // undefined / null
```
