### ISSUE TITLE
Invalid 'issuer' parameter

### ISSUE THREAD

**Issue by rodriguesabner** [hectorm/otpauth#25]
Hi! First thanks for the lib, it helps me a lot.

The problem,

I have this Issuer:
`totp/Slack%20(Name%20Company%20Wonderfoul):guest@mailer.com`

When I get to the snippet:
 `uriParams.issuer === uriLabel[0]`

I get the error: **Invalid 'issuer' parameter**;

----

Does the uriParams.issuer really need to be the same as the uriLabel?

I managed to handle it as follows:
` uriLabel[0].split(" ")[0]`

Or just ignore this condition.

What do you think?

**Comment by hectorm** [comment]
According to the key URI format, if the issuer and the label are both defined they should be equal.

> STRONGLY RECOMMENDED: The issuer parameter is a string value indicating the provider or service this account is associated with, URL-encoded according to [RFC 3986](http://tools.ietf.org/html/rfc3986). If the issuer parameter is absent, issuer information may be taken from the issuer prefix of the label. If both issuer parameter and issuer label prefix are present, they should be equal.

https://github.com/google/google-authenticator/wiki/Key-Uri-Format#issuer

**Comment by rodriguesabner** [comment]
> Older Google Authenticator implementations ignore the issuer parameter and rely upon the issuer label prefix to disambiguate accounts. Newer implementations will use the issuer parameter for internal disambiguation, it will not be displayed to the user. We recommend using both issuer label prefix and issuer parameter together to safely support both old and new Google Authenticator versions.

Can I have the optional issuer if I fall into this "old implementations" scenario? Or can I somehow bypass this? Unfortunately it is a real scenario with the

issuer= Slack + Company Name
issuer=Slack

**Comment by rodriguesabner** [comment]
I believe I can redo the URL, replicating the issuer's name, so I wouldn't suffer if I had multiple Slacks connected, right?

**Comment by hectorm** [comment]
What service is generating these invalid URIs? I see references to Slack but it's not clear to me if this service is generating them.

Could you share an example with the full URI? Obviously with the secret redacted.

**Comment by rodriguesabner** [comment]
That's Slack itself! Sure:

`otpauth://totp/Slack%20(My%20Big%20Corp):<email>?secret=<secret>&issuer=Slack`.

-------

I solved it as follows, I tested it in Slack and it worked, it recognized my integration.

https://github.com/rodriguesabner/authenticator-back/blob/master/src/common/BaseService.ts

**Comment by hectorm** [comment]
After analyzing the behavior of some applications, these were the results in case the issuer as label prefix and parameter don't match:

* **Aegis:** prefers label prefix.
* **FreeOTP:** prefers label prefix.
* **Google Authenticator:** uses the format "issuer parameter (full label)".
* **Microsoft Authenticator:** prefers label prefix.

Also since the key URI format says "should" and not "must" I'm going to follow the behavior of most applications and prefer the label prefix.

Could you confirm if d24e9ca487aa1981fbd91f655ef2097ed3f0009d solves your problem?

**Comment by rodriguesabner** [comment]
Nice, now is working, thanks hector!

**Comment by hectorm** [comment]
Thank you very much for verifying it, I've just published the 7.1.0 version with this change.
