### ISSUE TITLE
Add "browser" field to package.json

### ISSUE THREAD

**Issue by philer-jambit** [hectorm/otpauth#260]
In `package.json` there is currently an entry `"main": "./dist/otpauth.node.cjs",`. There is also `"exports"` which contains the `"default": "./dist/otpauth.esm.js"`.
My suggestion is to add  `"browser": "./dist/otpauth.esm.js",` next to `"main"`. This allows bundlers to find the correct entry points when resolving modules for the web.

---

**My problem:**
I'm trying to use `otpauth` in Cypress end-to-end tests. Cypress compiles test files via webpack to be run in a browser environment. However with the current configuration in `package.json` it throws an error:
```
Error: Webpack Compilation Error
./node_modules/otpauth/dist/otpauth.node.cjs
Module not found: Error: Can't resolve 'node:crypto' in '/path/to/my/project/node_modules/otpauth/dist'
resolve 'node:crypto' in '/path/to/my/project/node_modules/otpauth/dist'
  Parsed request is a module
  using description file: /path/to/my/project/node_modules/otpauth/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
```
As you can see it is trying to import the node version rather than the esm version of the package.  
Note the last line about the missing `"browser"` configuration. Adding the line I've suggested above fixes the compilation error.

Edit: I'm importing in a typescript file like this:
```ts
import { TOTP } from "otpauth"
```
If I instead import like this:
```ts
import { TOTP } from "../../node_modules/otpauth/dist/otpauth.esm.js"
```
it works, but I lose all type checking information as the `.d.ts` file can no longer be resolved.

**Comment by hectorm** [comment]
Done!

**Comment by philer-jambit** [comment]
That was quick! Thank you :)
