### ISSUE TITLE
Validate is broken and considers single digit tokens as valid.

### ISSUE THREAD

**Issue by TheGrandmother** [hectorm/otpauth#3]
So.
I found when debugging some error handling stuff that using "1" as a token was considered valid. I only had `delta !== null` check to see if the token was valid and the single digit token returned a negative integer so the check passed.

On further exploration I found that single digit tokens very often return integers indicating a valid token.

Here is some code to recreate it:
```javascript
const OTPAuth = require("otpauth");

const totp = new OTPAuth.TOTP({
  algorithm: "SHA1",
  digits: 6,
  period: 30,
  secret: OTPAuth.Secret.fromB32("NB2W45DFOIZA")
});

const token = totp.generate();

let delta = totp.validate({window: 10, token: token});
console.log(`Valid token "${token}" has delta ${delta}`);

delta = totp.validate({window: 10, token: "420420"});
console.log(`Invalid token has delta ${delta}`);

let deltas = {};
for (let i = 0; i < 10; i++) {
  deltas[i] = totp.validate({
    window: 10,
    token: `${i}`
  });
}
console.log("Single digit tokens:", deltas);

```
Output:
```
Valid token "102040" has delta 0
Invalid token has delta null
Single digit tokens: {
  '0': 0,
  '1': 7,
  '2': -6,
  '3': -8,
  '4': -3,
  '5': null,
  '6': 2,
  '7': -2,
  '8': -9,
  '9': -10
}
```

Changing `window`, `period` or `digits` gives similar results.

Tested on otpauth `v3.2.7`.
Running node `v12.1.0`.

**Comment by hectorm** [comment]
My bad, I forgot to pad the input token in the validation method. The new version I just published (3.2.8) fixes this problem, could you confirm that the vulnerability has been fixed?

**Comment by TheGrandmother** [comment]
The above snippet does no longer generate the unexpected behavior.
Thanks for the quick fix!
:+1:

**Comment by hectorm** [comment]
Thanks to you for the discovery!
