### ISSUE TITLE
How to solve this  ?

### ISSUE THREAD

**Issue by mohdlatif** [hectorm/otpauth#304]
```
file:///root/totpauth/node_modules/otpauth/dist/otpauth.node.mjs:77
  if (crypto?.createHmac) {
             ^

SyntaxError: Unexpected token '.'
```

![image](https://github.com/hectorm/otpauth/assets/56746772/5f33f79d-f2fa-41d1-abbf-f05ecea28ebe)

**Comment by hectorm** [comment]
It seems that the environment in which you are running the code does not support the [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operator.

If you are using a version of Node.js lower than 16, you should upgrade to one of the [supported versions](https://github.com/nodejs/release#release-schedule).
