### ISSUE TITLE
Package doesn't work for devices other than iOS

### ISSUE THREAD

**Issue by LilFatFrank** [hectorm/otpauth#397]
We tried android, windows
The OTPAuth library only works for iOS on phone.
Not even on an extension.

**Comment by hectorm** [comment]
This library definitely works on those platforms. In order to help you, I would need more details about your scenario, a code example and which JS runtime you are running it in so that I can reproduce it.

**Comment by LilFatFrank** [comment]
It works for certain browser extensions on mac and windows
on iOS, it didn't work for authy extension and none on android whatsoever

Here are the details:
node:16

imports
`import { TOTP } from "otpauth";
import qrCode from "qrcode";`

setup
`const totp = new TOTP({
                issuer: "OTPAUTH",
                label: email,
                algorithm: "SHA1",
                digits: 6,
                period: 60,
              });

              const otpUrl = totp.toString();
              let qrString = "";

              qrString = await qrCode.toDataURL(otpUrl);`
              
testing
`const decryptedSecret = storedSecret;
        const totp = new TOTP({
          secret: decryptedSecret,
          algorithm: "SHA1",
          digits: 6,
          period: 60,
        });

        const expectedOTP = totp.generate();`  
        
        
Let me know if you need more details

**Comment by hectorm** [comment]
I just ran the test suite against Node.js 16 and it passes without errors although it is an EOL version and you should upgrade.

TOTP is time based, do both devices have the clock synchronized?

In the sample code I see a period of 60 seconds when the usual is 30 seconds. Does the application use the same period?

**Comment by LilFatFrank** [comment]
I see, I can change that to 30 seconds and run tests

**Comment by LilFatFrank** [comment]
It works with changing time to 30
