### ISSUE TITLE
TOTP validation not working

### ISSUE THREAD

**Issue by Samir-NT** [hectorm/otpauth#441]
## Goal
Trying to validate a TOTP token for a given secret. 

## Description
Expected behaviour:
- correct token: alert success/delta not null
- wrong token: alert with the correct and **different** token for the current time/delta is null

Observed behaviour:
- correct token: delta is null, generated token is equal to input token
- wrong token: delta is null, generated token as expected

The behaviour is the same when I swap the position of generation and validation.  
## Test
The code below is almost directly taken from the README.  
```
<!DOCTYPE html>
<html>
  <body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/otpauth/9.1.5/otpauth.umd.min.js"></script>
  <script>
    let totp = new OTPAuth.TOTP({
    issuer: "ACME",
    label: "AzureDiamond",
    algorithm: "SHA1",
    digits: 6,
    period: 30,
    secret: "NB2W45DFOIZA",
  });

  // Validate a token (returns the token delta or null if it is not found in the search window, in which case it should be considered invalid).
  let token = prompt("TOTP: ");
  let delta = totp.validate({ token, window: 1 });
  if (delta) {
    alert("You got lucky.. this time");
  } else {
    alert("Wrong TOTP: " + totp.generate());
  }
  </script>
  </body>
</html>
```

**Comment by hectorm** [comment]
You must explicitly check if `delta` is `null` (`delta !== null`), otherwise in your example it will evaluate to `false` if its value is `0`.

**Comment by Samir-NT** [comment]
Well this is just embarassing, didn't even think about checking the real value of delta before opening this report.  
Sorry for the noise!

**Comment by hectorm** [comment]
Don't worry, thanks anyway for taking the time to open an issue about something you thought was wrong!
