### ISSUE TITLE
Getting Invalid OTP Code

### ISSUE THREAD

**Issue by Mobeen-Ghaffar** [hectorm/otpauth#468]
Generate 2FA code is invalid and different as google authenticator . 
Here is my code:
```
let code="screte_code_here";
 let totp = new OTPAuth.TOTP({
          
          algorithm: 'SHA1',
          digits: 6,
          secret: code,
        });
        // Generate a token.
        let token = totp.generate();
        let delta = totp.validate({
          token: token,
          window: 1
        });
        if(delta!=null){
         console.log("Valid Code")
        }
        
  ```
  Sometime generated code is correct and sometime its wrong. Any idea why?

**Comment by hectorm** [comment]
Is the clock synchronized between the two devices?

**Comment by Mobeen-Ghaffar** [comment]
No

**Comment by Mobeen-Ghaffar** [comment]
> Is the clock synchronized between the two devices?

No

**Comment by hectorm** [comment]
Well, that's your problem, TOTP (Time-based One-Time Password) uses time as a counter to calculate the token.

**Comment by Mobeen-Ghaffar** [comment]
Its happened with other secrete token as well. 
For those, I am not using authenticator app. I am directly using secrete token in code. Why its happening for those as well?

> Well, that's your problem, TOTP (Time-based One-Time Password) uses time as a counter to calculate the token.

**Comment by Mobeen-Ghaffar** [comment]
> Any help how can I handle this? I don't have timezone of secrete token? 
> 
> > Well, that's your problem, TOTP (Time-based One-Time Password) uses time as a counter to calculate the token.

**Comment by hectorm** [comment]
You don't need to do anything with time zones, just make sure the devices have their clocks synchronized. Normally this is done automatically through [NTP](https://en.wikipedia.org/wiki/Network_Time_Protocol), but that is completely unrelated to this library.

**Comment by Mobeen-Ghaffar** [comment]
Make sense. Thank for your time.
