### ISSUE TITLE
To much code generation with a window size + 1

### ISSUE THREAD

**Issue by air2** [hectorm/otpauth#487]
Currently when specifying a window size, all codes within that window are generated. I think this is done to keep the timing equal for every code checked. I think this is done against timing attacks? However, I do not see any drawbacks of an attacker seeing which timed code is accepted. In other words when 3 codes are generated (a window of size 1) and an attacker would now the code is matched against number 2, the attacker gains no real info. (in contrary to individual digits in the code, which should ALWAYS ALL be checked)

So I do not see any draw backs to generate the code for counter 0 end if it not matches for counter - 1 if it not matches for counter + 1 etc. until a match is found, this would improve the matching speed and reduce the number of calculations to be performed when checking codes (Especially with bigger window sizes). (Because mostly the time of the client will be equal, or close to equal to the server) So this will only gives a penalty when the client clock is off, or the client is providing a just expired token (and the window stills allows it, or when the client provides an non valid token) instead of calculating the codes always.

If this agreed upon I would happily provide a pull request implementing this (IMHO) optimisation. But maybe I am overlooking something, so please let me know if this somehow a bad idea.

**Comment by hectorm** [comment]
This behavior was introduced to prevent timing attacks, but I also agree that the attacker would not gain any useful information in this scenario.

A pull request to change the verification method to end on the first match would be welcome, as long as the comparison of generated and expected token remains in constant time.
