### ISSUE TITLE
Adding image to the totp  object

### ISSUE THREAD

**Issue by MHF0** [hectorm/otpauth#492]
I am trying to integrate our company's logo into the OTPAuth TOTP object for better branding and visual identification. Currently, the object is initialized as follows:

```js
const totp = new OTPAuth.TOTP({
   issuer: "Company name",
   label: "label",
   algorithm: "SHA1",
   digits: 6,
   period: 30,
   secret: OTPAuth.Secret.fromBase32(secret),
});
```

I would like to know the process or method to include our company logo alongside the issuer name in the TOTP object. Any guidance or suggestions on achieving this would be greatly appreciated. Thank you!

**Comment by hectorm** [comment]
You should not use the TOTP object of this library to store any additional metadata, instead store the data you need in your own data structure.
