### ISSUE TITLE
Add `type` property

### ISSUE THREAD

**Issue by hicallmeal** [hectorm/otpauth#519]
When dealing with multiple tokens of differing type (hotp/totp/custom (out of scope of OTPAuth)), it'd be good to be able to distinguish them according to type, so that it's easier to perform type specific operations (UI, sorting, etc).

The default would be `totp` and HMAC tokens would be `hotp`. 

I think it should be easy enough to implement; during URI parsing, add it to `config` https://github.com/hectorm/otpauth/blob/a53054fc7b54b285f598c9dd632caabaa8c21b2e/src/uri.js#L77

And the classes can add it to the defaults.

Can attempt a pull request if you'd like.

**Comment by hectorm** [comment]
You can actually check the type with `instanceof` ([see example](https://github.com/hectorm/otpauth/blob/a057994bb76ba52058286990d2353cff2dec2b2b/src/uri.js#L154)), isn't that enough for your use case?

**Comment by hicallmeal** [comment]
I admittedly didn't know/check for that, thank you. 
Unfortunately, that's more of a check / expression, where I'd rather directly get a property there's also ascertained certainty. 
And it feels a little expensive checking that way - but, I have no idea on that!

All good though, thank you for the advice!
