### ISSUE TITLE
大哥你好，为什么不尝试提供通过订阅地址创建TOTP实例的方法呢

### ISSUE THREAD

**Issue by gjynb** [hectorm/otpauth#529]
不同的用户生成TOTP的参数也不相同，如果能直接通过订阅地址去创建TOTP实例那我将很开心，否则我依然需要保存除订阅地址以外的内容

**Comment by gjynb** [comment]
1. 如今效果，在仅做校验令牌时不是很轻便
![WechatIMG90](https://github.com/user-attachments/assets/48fef456-f944-4491-92a2-1d32a41d1a94)
2. 能否添加如下方式创建TOTP实例
![WechatIMG91](https://github.com/user-attachments/assets/e6c1fae9-cb3b-4a7e-9c5d-662259701f88)

**Comment by gjynb** [comment]
我英语成绩十分糟糕，害怕通过翻译的英语会和我本意不一致，所以冒犯采用中文的形式提问，望大哥体谅

**Comment by hicallmeal** [comment]
看起来您正在寻找可以单独使用的 `OTPAuth.URI.parse("otpauth//...")` // `const totp = OTPAuth.URI.parse("...")` 并返回 `{issuer: "foo", label: "bar", ..}`

这就是您要找的吗？

**Comment by gjynb** [comment]
这个方法我没有发现，确实这个方法能够满足我使用的场景，这就是我要找的，原来已经存在了
