### ISSUE TITLE
Set default value to HOTP.validate({digits})

### ISSUE THREAD

**Issue by floriannari** [hectorm/otpauth#550]
For example, `HOTP.generate({digits})` has `HOTP.defaults.digits` (i.e. 6) for default value.
But for `HOTP.validate({digits})`, we have to define `digits: 6`.

I suggest that the “digits” parameter of the “validate” function also use `HOTP.defaults.digits` for default value.

Thanks

**Comment by hectorm** [comment]
Sounds reasonable, I just did it. Thanks!
