### ISSUE TITLE
TypeError: str.replaceAll is not a function

### ISSUE THREAD

**Issue by jkao1017** [hectorm/otpauth#554]
I believe patch 9.3.3 introduced the use of replaceAll in order to allow spaces in base32 and hex encoded secrets. I am working on a project that is using node 14 which does not support replaceAll. Would it be possible to use replace instead?

**Comment by hectorm** [comment]
Node.js was discontinued on 30 April 2023, I can't guarantee compatibility with unsupported versions. However, you can continue to use OTPAuth v9.3.2 until you can upgrade Node.js.
