### ISSUE TITLE
[Question] Has this been tested in Cloudflare (Edge runtime)?

### ISSUE THREAD

**Issue by rohanrehman** [hectorm/otpauth#572]
This looks great! currently using Authjs with NEXT deployed on Clouflared Pages.
Has this been tested on nodejs Edge runtime?

Thanks.

**Comment by hectorm** [comment]
Although the CI does not run the tests on Edge runtime, in the past I have verified that at least it works on Cloudflare Workers, if you find any incompatibility let me know and I will fix it.
