### ISSUE TITLE
cannot import name 'OtpAuth' from 'otpauth'

### ISSUE THREAD

**Issue by tltc1020** [hectorm/otpauth#575]
File "/home/lighthouse/OnlineJudge/account/urls/oj.py", line 3, in <module>
    from ..views.oj import (ApplyResetPasswordAPI, ResetPasswordAPI,

  File "/home/lighthouse/OnlineJudge/account/views/oj.py", line 12, in <module>
    from otpauth import OtpAuth

ImportError: cannot import name 'OtpAuth' from 'otpauth' (/home/lighthouse/.local/lib/python3.8/site-packages/otpauth/__init__.py)

help~

**Comment by hakancodes0** [comment]
Import the way as mentioned on docs.

import * as OTPAuth from "otpauth";

**Comment by hectorm** [comment]
I think you are confusing this project with a Python library of the same name.
